FROM golang:1.17 as builder

WORKDIR /go/src/app

RUN cd /go/src/app

COPY app .

RUN go build hello.go



FROM alpine:3.14

WORKDIR /go/src/app

COPY --from=builder /go/src/app/hello .

ENTRYPOINT ./hello